stages:
  - build:sid_source_pytest
  - test:sid_source_pytest

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME_SID: sid:latest
  IMAGE_DESTINATION_SID: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SID
  IMAGE_NAME_SID_SOURCE: sid_source:latest
  IMAGE_DESTINATION_SID_SOURCE: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SID_SOURCE
  IMAGE_NAME_SID_SOURCE_PYTEST: sid_source_pytest:latest
  IMAGE_DESTINATION_SID_SOURCE_PYTEST: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SID_SOURCE_PYTEST
  IMAGE_NAME_BULLSEYE: bullseye:latest
  IMAGE_DESTINATION_BULLSEYE: $CI_REGISTRY_IMAGE/$IMAGE_NAME_BULLSEYE
  IMAGE_NAME_KINETIC: kinetic:latest
  IMAGE_DESTINATION_KINETIC: $CI_REGISTRY_IMAGE/$IMAGE_NAME_KINETIC
  IMAGE_NAME_JAMMY: jammy:latest
  IMAGE_DESTINATION_JAMMY: $CI_REGISTRY_IMAGE/$IMAGE_NAME_JAMMY
  IMAGE_NAME_FOCAL: focal:latest
  IMAGE_DESTINATION_FOCAL: $CI_REGISTRY_IMAGE/$IMAGE_NAME_FOCAL
  IMAGE_NAME_SPACK_CENTOS: spack-centos:latest
  IMAGE_DESTINATION_SPACK_CENTOS: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SPACK_CENTOS
  IMAGE_NAME_SPACK_CUDA: spack-cuda:latest
  IMAGE_DESTINATION_SPACK_CUDA: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SPACK_CUDA
  IMAGE_NAME_SPACK_BULLSEYE: spack-bullseye:latest
  IMAGE_DESTINATION_SPACK_BULLSEYE: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SPACK_BULLSEYE
  IMAGE_NAME_SPACK_JAMMY: spack-jammy:latest
  IMAGE_DESTINATION_SPACK_JAMMY: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SPACK_JAMMY
  IMAGE_NAME_SPACK_FOCAL: spack-focal:latest
  IMAGE_DESTINATION_SPACK_FOCAL: $CI_REGISTRY_IMAGE/$IMAGE_NAME_SPACK_FOCAL

build sid source_pytest:
  stage: build:sid_source_pytest
  allow_failure: false
  tags:
    - ci.inria.fr
    - large
  image: docker:stable
  before_script:
    - docker image prune --filter="dangling=true" --force
    - docker rmi $IMAGE_DESTINATION_SID_SOURCE_PYTEST --force
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --no-cache --force-rm -t $IMAGE_DESTINATION_SID_SOURCE_PYTEST -f ${CI_PROJECT_DIR}/docker_recipes/Dockerfile_Debian_Sid_Source_Pytest .
    - docker push $IMAGE_DESTINATION_SID_SOURCE_PYTEST
    - echo "Image ${IMAGE_NAME_SID_SOURCE_PYTEST} successfully pushed to ${IMAGE_DESTINATION_SID_SOURCE_PYTEST}"

test sid source_pytest:
  stage: test:sid_source_pytest
  allow_failure: true
  tags:
    - ci.inria.fr
    - large
  image: docker:stable
  script:
    - docker run $IMAGE_DESTINATION_SID_SOURCE_PYTEST
    - echo "Test successfully passed for image ${IMAGE_NAME_SID_SOURCE_PYTEST} in ${IMAGE_DESTINATION_SID_SOURCE_PYTEST}"
