FROM ubuntu:focal as builder

USER 0

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y wget

### PDI package install
RUN echo "deb [ arch=amd64 ] https://raw.githubusercontent.com/pdidev/repo/ubuntu focal main" | tee /etc/apt/sources.list.d/pdi.list > /dev/null
RUN wget -O /etc/apt/trusted.gpg.d/pdidev-archive-keyring.gpg https://raw.githubusercontent.com/pdidev/repo/ubuntu/pdidev-archive-keyring.gpg
RUN chmod a+r /etc/apt/trusted.gpg.d/pdidev-archive-keyring.gpg /etc/apt/sources.list.d/pdi.list
RUN apt-get update -y
RUN apt install -y pdidev-archive-keyring

### Custom packages
RUN wget https://gac.udc.es/~emilioj/focal.tgz
RUN tar -xf focal.tgz
WORKDIR /focal
RUN apt install -y `find . -name "*.deb"`

### Image config
ENV VIRTUAL_ENV /opt/gym_dssat_pdi
ENV PATH "${VIRTUAL_ENV}/bin:${PATH}"
RUN echo "export PATH=${PATH}" >> /etc/profile

RUN useradd -ms /bin/bash gymusr
USER gymusr
WORKDIR /home/gymusr
ENV BASH_ENV=/etc/profile
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash", "-c"]

CMD ["python /opt/gym_dssat_pdi/lib/python3.8/site-packages/gym_dssat_pdi_samples/run_env.py"]
