FROM centos:latest

USER 0

RUN cd /etc/yum.repos.d/ \
&& sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
&& sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# Install Spack requirements
RUN yum makecache
RUN yum update -y
RUN yum install -y epel-release
RUN yum update -y
RUN yum --enablerepo epel groupinstall -y "Development Tools"
RUN yum --enablerepo epel install -y curl findutils gcc-c++ gcc gcc-gfortran git gnupg2 hostname iproute redhat-lsb-core make patch python3 python3-pip python3-setuptools unzip
RUN yum install -y --allowerasing ca-certificates coreutils curl environment-modules gcc-gfortran git gpg redhat-lsb python3 unzip zip python3-distutils-extra virtualenv
RUN python3 -m pip install boto3

RUN useradd -ms /bin/bash gymusr
USER gymusr
WORKDIR /home/gymusr
ENV BASH_ENV=/etc/profile
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash", "-c"]

# 1. Get and enable Spack (version 0.19.0, last stable when writing this recipe)
RUN git clone --branch v0.19.0 -c feature.manyFiles=true https://github.com/spack/spack.git 
RUN git clone https://github.com/pdidev/spack.git spack/var/spack/repos/pdi
RUN git clone https://gitlab.inria.fr/rgautron/gym_dssat_pdi-spack.git spack/var/spack/repos/gym-dssat-pdi

RUN . spack/share/spack/setup-env.sh \
&& spack repo add spack/var/spack/repos/pdi \
&& spack repo add spack/var/spack/repos/gym-dssat-pdi \
&& spack install gym-dssat \
&& spack env create gym-dssat-pdi spack/var/spack/repos/gym-dssat-pdi/env/spack.yaml \
&& spack env activate gym-dssat-pdi \
&& spack concretize

CMD [". spack/share/spack/setup-env.sh && spack env activate gym-dssat-pdi && python spack/gym-dssat-pdi/samples/run_env.py"]

### Build the Docker image
# docker build . -t "gym-dssat:centos-spack" -f Dockerfile_CentOS_Spack
#
### Run the default example in the Docker image:
# docker run gym-dssat:centos-spack
#
### Interactively run the gym-dssat-pdi environment in the Docker image:
# docker run -it gym-dssat:centos-spack bash
# ~$ source spack/share/spack/setup-env.sh
# ~$ spack env activate gym-dssat-pdi
# ~$ python spack/gym-dssat-pdi/samples/run_env.py
