FROM debian:sid as builder

USER 0

RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get upgrade -y --no-install-recommends \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
&& rm -rf /var/lib/apt/lists/*

### PDI package install
RUN echo "deb [ arch=amd64 ] https://raw.githubusercontent.com/pdidev/repo/debian sid main" | tee /etc/apt/sources.list.d/pdi.list > /dev/null
RUN wget -O /etc/apt/trusted.gpg.d/pdidev-archive-keyring.gpg https://raw.githubusercontent.com/pdidev/repo/debian/pdidev-archive-keyring.gpg
RUN chmod a+r /etc/apt/trusted.gpg.d/pdidev-archive-keyring.gpg /etc/apt/sources.list.d/pdi.list

# Temporary workaround to guarantee the updated tarball is downloaded
# and we are using up-to-date debian packages
#
# Calls for a random number to break the caching of the following wget
# (https://stackoverflow.com/questions/35134713/disable-cache-for-specific-run-commands/58801213#58801213)
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends \
    pdidev-archive-keyring \
&& rm -rf /var/lib/apt/lists/*

RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends \
    pdidev-archive-keyring \
    libpdi-dev \
    pdiplugin-pycall \
    cmake \
    make \
    gcc \
    g++ \
    gfortran \
    pkg-config \
    python3-pip \
    python3-dev \
    git \
&& rm -rf /var/lib/apt/lists/*

# DSSAT_PDI INSTALLATION
RUN git clone --recurse-submodules https://gitlab.inria.fr/rgautron/gym_dssat_pdi.git
RUN mkdir /gym_dssat_pdi/dssat-csm-os/build
WORKDIR /gym_dssat_pdi/dssat-csm-os/build
RUN cmake -DCMAKE_INSTALL_PREFIX='/opt/dssat_pdi' \
          -DCMAKE_PREFIX_PATH='/usr/share/paraconf/cmake' \
          ../
RUN make
RUN make install

# # COPY DSSAT FILES
WORKDIR /gym_dssat_pdi
RUN mv dssat-csm-data/* /opt/dssat_pdi/
# RUN python3 -m pip install setuptools==65.6.3 wheel==0.38.4 \
#                            matplotlib==3.3.4 numpy==1.24.1 pyzmq==25.0.0 \
#                            gym==0.21.0
RUN python3 -m pip install -e ./gym-dssat-pdi

### Image config
ENV VIRTUAL_ENV /opt/gym_dssat_pdi
ENV DSSAT_PATH /opt/dssat_pdi
ENV PATH "${VIRTUAL_ENV}/bin:${DSSAT_PATH}:${PATH}"
RUN echo "export PATH=${PATH}" >> /etc/profile

RUN bash -l -c 'echo export GYM_DSSAT_PDI_PATH="/opt/gym_dssat_pdi/lib/$(python3 -V | tr -d '[:blank:]' | tr '[:upper:]' '[:lower:]' | sed 's/\.[^.]*$//')/site-packages/gym_dssat_pdi" >> /etc/bash.bashrc'

RUN useradd -ms /bin/bash gymusr
USER gymusr
WORKDIR /home/gymusr
ENV BASH_ENV=/etc/profile
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash", "-c"]

CMD ["python3 /gym_dssat_pdi/gym-dssat-pdi/gym_dssat_pdi_samples/run_env.py"]

### Build the Docker image
# docker build . -t "gym-dssat:debian-sid-source" -f Dockerfile_Debian_Sid_Source
#
### Run the default example in the Docker image:
# docker run gym-dssat:debian-sid-source
#
### Interactively run the gym-dssat-pdi environment in the Docker image:
# docker run -it gym-dssat:debian-sid-source bash
# ~$ python3 /gym_dssat_pdi/gym-dssat-pdi/gym_dssat_pdi_samples/run_env.py
