[metadata]
name = gym_dssat_pdi
#version = attr: gym_dssat_pdi.__version__
version = 0.0.1
description = Middleware to connect OpenAI Gym with DSSAT-PDI and create customized Gyms
long_description = file: README.md
classifiers =
        Development Status :: 2 - Pre-Alpha
        Intended Audience :: Developers
        Topic :: System :: Archiving :: Packaging
        License :: OSI Approved :: BSD-3-Clause
        Programming Language :: Python
        Programming Language :: Python :: 3
        Programming Language :: Python :: 3.6
        Programming Language :: Python :: 3.7
        Programming Language :: Python :: 3.8
        Programming Language :: Python :: 3.9
author = Romain Gautron
author_email = romain.gautron@cirad.fr
maintainer = Emilio J. Padrón
maintainer_email = emilioj@udc.gal
url = https://gitlab.inria.fr/rgautron/gym_dssat_pdi
keywords = crop management, reinforcement learning
license = BSD-3-Clause

[options]
packages = find:
install_requires =
      gym == 0.18.3
      numpy
      matplotlib
      jinja2
      pyzmq
      psutil
      pyyaml
      pympler # needed for gym_dssat_pdi_samples/run_env.py

[options.package_data]
gym_dssat_pdi = envs/configs/*.yml, envs/configs/*.jinja2
